platform :ios, '9.2'

def network_pods
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireImage', '~> 3.1'
end

def layout_pods
  pod 'SnapKit', '~> 3.1.2'
end

def shared_pods
  network_pods
  layout_pods
end

target 'Couch' do
  use_frameworks!

  shared_pods

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
